project:
  type: website

website:
  title: "Workshop R"
  page-footer: "Made with [Quarto](https://quarto.org/) by [Deri Siswara](https://derisiswara.org/about.html) - [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)."
  navbar:
    left:
      - href: index.qmd
        text: Home
#      - href: about.qmd
#        text: About
#      - href: coc.qmd
#        text: Code of Conduct

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true

  revealjs: 
    theme: [default, custom.scss]
    width: 1600
    height: 900
    slide-number: true
    logo: "images/smu logo.png"
    fig-height: 8
    fig-width: 15
    footer: "[SEIC x DSA Python for Macroeconomics](https://bellaratmelia.github.io/2024-python-macroecons/)"



